import os

os.makedirs('src', exist_ok=True)
os.makedirs('results', exist_ok=True)
os.makedirs('data', exist_ok=True)

with open('main.py', 'w', encoding='utf-8') as f:
    f.write('import sys, os\n')
    f.write('sys.path.insert(0, "src")\n')
    f.write('from data_generator import generate\n')
    f.write('from signal_monitor import run_monitoring\n')
    f.write('from visualiser import plot_dashboard\n')
    f.write('from report_generator import generate_text_report\n')
    f.write('os.makedirs("results", exist_ok=True)\n')
    f.write('print("Running Galileo / GPS Signal Quality Monitor...")\n')
    f.write('print("Using synthetic data calibrated to Galileo E1 OS signal characteristics")\n')
    f.write('print("")\n')
    f.write('df = generate(duration_hours=6, inject_events=True)\n')
    f.write('print("Loaded " + str(len(df)) + " observations | " + str(df["sv"].nunique()) + " SVs | " + str(df["epoch"].nunique()) + " epochs")\n')
    f.write('print("")\n')
    f.write('result = run_monitoring(df)\n')
    f.write('plot_dashboard(df, result, output_dir="results")\n')
    f.write('generate_text_report(df, result, output_dir="results")\n')
    f.write('print("")\n')
    f.write('print("Done! Check the results/ folder:")\n')
    f.write('print("  monitoring_dashboard.png  - open this to see the plots")\n')
    f.write('print("  monitoring_report.txt     - structured performance report")\n')

with open('src/signal_monitor.py', 'w', encoding='utf-8') as f:
    f.write('import numpy as np\n')
    f.write('import pandas as pd\n')
    f.write('from dataclasses import dataclass\n')
    f.write('\n')
    f.write('CN0_THRESHOLD = 32.0\n')
    f.write('MIN_SVS = 4\n')
    f.write('GAP_S = 90\n')
    f.write('\n')
    f.write('@dataclass\n')
    f.write('class MonitoringResult:\n')
    f.write('    availability_pct: dict\n')
    f.write('    cn0_stats: pd.DataFrame\n')
    f.write('    anomalies: pd.DataFrame\n')
    f.write('    gaps: pd.DataFrame\n')
    f.write('    epoch_stats: pd.DataFrame\n')
    f.write('    summary_status: str\n')
    f.write('    galileo_gps_delta: float\n')
    f.write('\n')
    f.write('def compute_availability(df):\n')
    f.write('    total = df["epoch"].nunique()\n')
    f.write('    result = {}\n')
    f.write('    for const in df["constellation"].unique():\n')
    f.write('        valid = df[(df["constellation"] == const) & df["valid"]]\n')
    f.write('        per_epoch = valid.groupby("epoch")["sv"].nunique()\n')
    f.write('        available = (per_epoch >= MIN_SVS).sum()\n')
    f.write('        result[const] = round(100.0 * available / total, 2)\n')
    f.write('    return result\n')
    f.write('\n')
    f.write('def compute_cn0_stats(df):\n')
    f.write('    valid = df[df["valid"]].copy()\n')
    f.write('    valid["elev_band"] = pd.cut(valid["elevation"], bins=[0, 20, 40, 90],\n')
    f.write('                               labels=["Low (0-20deg)", "Mid (20-40deg)", "High (>40deg)"])\n')
    f.write('    return valid.groupby(["constellation", "elev_band"])["cn0"].agg(\n')
    f.write('        count="count", mean="mean", std="std",\n')
    f.write('        p5=lambda x: x.quantile(0.05)).round(2)\n')
    f.write('\n')
    f.write('def detect_anomalies(df):\n')
    f.write('    valid = df[df["valid"]].copy()\n')
    f.write('    anom = valid[valid["cn0"] < CN0_THRESHOLD].copy()\n')
    f.write('    anom["type"] = "Low C/N0"\n')
    f.write('    anom["severity"] = np.where(anom["cn0"] < 28, "SEVERE", "MODERATE")\n')
    f.write('    return anom.reset_index(drop=True)\n')
    f.write('\n')
    f.write('def detect_tracking_gaps(df):\n')
    f.write('    gaps = []\n')
    f.write('    for sv, grp in df[df["valid"]].groupby("sv"):\n')
    f.write('        grp = grp.sort_values("epoch")\n')
    f.write('        diffs = grp["epoch"].diff().dt.total_seconds()\n')
    f.write('        mask = diffs > GAP_S\n')
    f.write('        for epoch, gap_s in zip(grp["epoch"][mask], diffs[mask]):\n')
    f.write('            gaps.append({"sv": sv, "epoch": epoch, "gap_s": round(gap_s, 0),\n')
    f.write('                         "constellation": grp["constellation"].iloc[0]})\n')
    f.write('    return pd.DataFrame(gaps) if gaps else pd.DataFrame(\n')
    f.write('        columns=["sv", "epoch", "gap_s", "constellation"])\n')
    f.write('\n')
    f.write('def compute_epoch_stats(df):\n')
    f.write('    return df[df["valid"]].groupby(["epoch", "constellation"]).agg(\n')
    f.write('        sv_count=("sv", "nunique"),\n')
    f.write('        mean_cn0=("cn0", "mean"),\n')
    f.write('        min_elev=("elevation", "min")).reset_index()\n')
    f.write('\n')
    f.write('def run_monitoring(df):\n')
    f.write('    availability = compute_availability(df)\n')
    f.write('    cn0_stats = compute_cn0_stats(df)\n')
    f.write('    anomalies = detect_anomalies(df)\n')
    f.write('    gaps = detect_tracking_gaps(df)\n')
    f.write('    epoch_stats = compute_epoch_stats(df)\n')
    f.write('    gal = availability.get("Galileo", 0)\n')
    f.write('    status = "NOMINAL" if gal >= 99 else ("DEGRADED" if gal >= 95 else "CRITICAL")\n')
    f.write('    valid = df[df["valid"]]\n')
    f.write('    delta = round(valid[valid["constellation"]=="Galileo"]["cn0"].mean() -\n')
    f.write('                  valid[valid["constellation"]=="GPS"]["cn0"].mean(), 2)\n')
    f.write('    return MonitoringResult(availability_pct=availability, cn0_stats=cn0_stats,\n')
    f.write('        anomalies=anomalies, gaps=gaps, epoch_stats=epoch_stats,\n')
    f.write('        summary_status=status, galileo_gps_delta=delta)\n')

with open('src/data_generator.py', 'w', encoding='utf-8') as f:
    f.write('import numpy as np\n')
    f.write('import pandas as pd\n')
    f.write('from datetime import datetime, timedelta\n')
    f.write('\n')
    f.write('GALILEO_SVS = ["E01","E02","E03","E04","E05","E07","E08","E09",\n')
    f.write('               "E11","E12","E14","E18","E19","E21","E24","E25",\n')
    f.write('               "E26","E27","E30","E31","E33","E36"]\n')
    f.write('GPS_SVS = ["G01","G03","G06","G07","G09","G11","G14","G17",\n')
    f.write('           "G19","G21","G22","G25","G28","G30","G31","G32"]\n')
    f.write('\n')
    f.write('def generate(duration_hours=6, sampling_rate_s=30, inject_events=True, seed=42):\n')
    f.write('    np.random.seed(seed)\n')
    f.write('    n = int(duration_hours * 3600 / sampling_rate_s)\n')
    f.write('    t0 = datetime(2026, 4, 27, 8, 0, 0)\n')
    f.write('    epochs = [t0 + timedelta(seconds=i * sampling_rate_s) for i in range(n)]\n')
    f.write('    records = []\n')
    f.write('    for sv in GALILEO_SVS + GPS_SVS:\n')
    f.write('        is_gal = sv.startswith("E")\n')
    f.write('        const = "Galileo" if is_gal else "GPS"\n')
    f.write('        base = 44.5 if is_gal else 42.5\n')
    f.write('        ps = np.random.randint(0, n // 3)\n')
    f.write('        pe = min(ps + np.random.randint(n // 3, int(n * 0.9)), n)\n')
    f.write('        sz = pe - ps\n')
    f.write('        me = np.random.uniform(25, 85)\n')
    f.write('        t = np.linspace(0, 3.14159, sz)\n')
    f.write('        elevs = np.maximum(5.0, me * np.sin(t) + np.random.normal(0, 0.3, sz))\n')
    f.write('        azims = np.linspace(np.random.uniform(0, 180), np.random.uniform(180, 360), sz)\n')
    f.write('        for j, i in enumerate(range(ps, pe)):\n')
    f.write('            elev = elevs[j]\n')
    f.write('            cn0 = base + 0.32 * elev + np.random.normal(0, 1.8)\n')
    f.write('            if inject_events:\n')
    f.write('                if 100 <= i <= 104 and sv in ["E01","E03","G07"]:\n')
    f.write('                    cn0 -= np.random.uniform(6, 12)\n')
    f.write('                if elev < 20 and np.random.random() < 0.08:\n')
    f.write('                    cn0 -= np.random.uniform(2, 7)\n')
    f.write('                if 300 <= i <= 315:\n')
    f.write('                    cn0 += np.random.normal(-1.5, 2.0)\n')
    f.write('            cn0 = max(18.0, round(cn0, 2))\n')
    f.write('            records.append({"epoch": epochs[i], "sv": sv, "constellation": const,\n')
    f.write('                "cn0": cn0, "elevation": round(elev, 2),\n')
    f.write('                "azimuth": round(azims[j] % 360, 1), "valid": elev >= 10 and cn0 >= 30})\n')
    f.write('    return pd.DataFrame(records)\n')

with open('src/visualiser.py', 'w', encoding='utf-8') as f:
    f.write('import matplotlib.pyplot as plt\n')
    f.write('import matplotlib.dates as mdates\n')
    f.write('import numpy as np\n')
    f.write('from pathlib import Path\n')
    f.write('\n')
    f.write('COLORS = {"Galileo": "#003087", "GPS": "#D4A017"}\n')
    f.write('\n')
    f.write('def plot_dashboard(df, result, output_dir="results"):\n')
    f.write('    Path(output_dir).mkdir(exist_ok=True)\n')
    f.write('    fig, axes = plt.subplots(2, 2, figsize=(15, 10))\n')
    f.write('    fig.suptitle("Galileo / GPS Signal Quality Monitor", fontsize=13, fontweight="bold")\n')
    f.write('    ep = result.epoch_stats\n')
    f.write('    ax = axes[0, 0]\n')
    f.write('    for c, col in COLORS.items():\n')
    f.write('        d = ep[ep["constellation"] == c]\n')
    f.write('        ax.plot(d["epoch"], d["sv_count"], color=col, lw=1.3, label=c)\n')
    f.write('    ax.axhline(4, color="red", ls="--", lw=0.9, label="Min 4 SVs")\n')
    f.write('    ax.set_title("Valid Satellite Count", fontsize=10, fontweight="bold")\n')
    f.write('    ax.set_ylabel("Satellites"); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)\n')
    f.write('    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))\n')
    f.write('    ax = axes[0, 1]\n')
    f.write('    for c, col in COLORS.items():\n')
    f.write('        d = ep[ep["constellation"] == c]\n')
    f.write('        ax.plot(d["epoch"], d["mean_cn0"], color=col, lw=1.3, label=c)\n')
    f.write('    ax.axhline(32, color="orange", ls="--", lw=0.9, label="Anomaly threshold")\n')
    f.write('    ax.set_title("Mean C/N0 per Epoch", fontsize=10, fontweight="bold")\n')
    f.write('    ax.set_ylabel("C/N0 (dB-Hz)"); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)\n')
    f.write('    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))\n')
    f.write('    ax = axes[1, 0]\n')
    f.write('    valid = df[df["valid"]]\n')
    f.write('    for c, col in COLORS.items():\n')
    f.write('        sub = valid[valid["constellation"] == c].sample(min(600, len(valid[valid["constellation"]==c])), random_state=42)\n')
    f.write('        ax.scatter(sub["elevation"], sub["cn0"], alpha=0.2, s=7, color=col, label=c)\n')
    f.write('    elev_r = np.linspace(10, 85, 50)\n')
    f.write('    ax.plot(elev_r, 44.5 + 0.32 * elev_r, "b--", lw=1, label="Galileo model", alpha=0.6)\n')
    f.write('    ax.set_title("C/N0 vs Elevation", fontsize=10, fontweight="bold")\n')
    f.write('    ax.set_xlabel("Elevation (deg)"); ax.set_ylabel("C/N0 (dB-Hz)")\n')
    f.write('    ax.legend(fontsize=8); ax.grid(True, alpha=0.3)\n')
    f.write('    ax = axes[1, 1]\n')
    f.write('    if len(result.anomalies) > 0:\n')
    f.write('        for c, col in COLORS.items():\n')
    f.write('            sub = result.anomalies[result.anomalies["constellation"] == c]\n')
    f.write('            if len(sub): ax.scatter(sub["epoch"], sub["cn0"], s=18, color=col, alpha=0.7, label=c)\n')
    f.write('    ax.axhline(32, color="red", ls="--", lw=0.9, label="Threshold 32 dB-Hz")\n')
    f.write('    ax.set_title("Anomaly Events", fontsize=10, fontweight="bold")\n')
    f.write('    ax.set_ylabel("C/N0 (dB-Hz)"); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)\n')
    f.write('    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))\n')
    f.write('    plt.tight_layout()\n')
    f.write('    out = output_dir + "/monitoring_dashboard.png"\n')
    f.write('    plt.savefig(out, dpi=150, bbox_inches="tight")\n')
    f.write('    plt.close()\n')
    f.write('    print("Dashboard saved: " + out)\n')

with open('src/report_generator.py', 'w', encoding='utf-8') as f:
    f.write('from datetime import datetime\n')
    f.write('from pathlib import Path\n')
    f.write('\n')
    f.write('def generate_text_report(df, result, station="Synthetic", output_dir="results"):\n')
    f.write('    sep = "=" * 72\n')
    f.write('    lines = [sep,\n')
    f.write('        "GNSS SIGNAL QUALITY MONITORING REPORT",\n')
    f.write('        "Galileo / GPS Multi-Constellation Performance Analysis",\n')
    f.write('        "Station     : " + station,\n')
    f.write('        "Generated   : " + datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),\n')
    f.write('        "Window      : " + str(df["epoch"].min()) + " to " + str(df["epoch"].max()),\n')
    f.write('        sep, "",\n')
    f.write('        "[1] SERVICE AVAILABILITY (>= 4 valid satellites)"]\n')
    f.write('    for const, avail in result.availability_pct.items():\n')
    f.write('        s = "OK" if avail >= 99 else ("WARN" if avail >= 95 else "CRIT")\n')
    f.write('        lines.append("  " + const.ljust(10) + str(avail).rjust(7) + "%   [" + s + "]")\n')
    f.write('    lines += ["", "[2] SIGNAL QUALITY - C/N0 Statistics"]\n')
    f.write('    lines.append(result.cn0_stats.to_string())\n')
    f.write('    n = len(result.anomalies)\n')
    f.write('    lines += ["", "[3] ANOMALIES DETECTED (threshold: 32 dB-Hz)",\n')
    f.write('              "  Total events: " + str(n)]\n')
    f.write('    if n > 0:\n')
    f.write('        lines.append("  Affected SVs: " + ", ".join(sorted(result.anomalies["sv"].unique())))\n')
    f.write('    lines += ["", "[4] SIGNAL CONTINUITY",\n')
    f.write('              "  Tracking gaps: " + str(len(result.gaps))]\n')
    f.write('    lines += ["", "[5] MULTI-SYSTEM COMPARISON",\n')
    f.write('              "  Galileo - GPS C/N0 delta: " + str(result.galileo_gps_delta) + " dB-Hz"]\n')
    f.write('    lines += ["", "[6] SUMMARY",\n')
    f.write('              "  Galileo Service Status: " + result.summary_status, "", sep]\n')
    f.write('    report = "\\n".join(lines)\n')
    f.write('    Path(output_dir).mkdir(exist_ok=True)\n')
    f.write('    with open(output_dir + "/monitoring_report.txt", "w") as f:\n')
    f.write('        f.write(report)\n')
    f.write('    print(report)\n')

print("All project files created successfully!")
print("")
print("Project structure:")
print("  main.py")
print("  src/signal_monitor.py")
print("  src/data_generator.py")
print("  src/visualiser.py")
print("  src/report_generator.py")
print("")
print("Now run:  python main.py")
